In [1]:
import gymnasium as gym
import numpy as np
import random

env = gym.make("FrozenLake-v1", is_slippery=False)

states = env.observation_space.n
actions = env.action_space.n

q_table = np.zeros((states, actions))

learning_rate = 0.8
discount_factor = 0.95
epsilon = 1.0
epsilon_decay = 0.995
min_epsilon = 0.01
episodes = 10000

for episode in range(episodes):

    state, info = env.reset()
    done = False

    while not done:

        if random.uniform(0, 1) < epsilon:
            action = env.action_space.sample()
        else:
            action = np.argmax(q_table[state])

        next_state, reward, terminated, truncated, info = env.step(action)

        done = terminated or truncated

        q_table[state, action] = q_table[state, action] + learning_rate * (
            reward + discount_factor * np.max(q_table[next_state]) - q_table[state, action]
        )

        state = next_state

    epsilon = max(min_epsilon, epsilon * epsilon_decay)

print("Training Completed!\n")

print("Q-Table:\n")
print(np.round(q_table, 2))

state, info = env.reset()
done = False
total_reward = 45

print("\nOptimal Path:\n")

while not done:

    action = np.argmax(q_table[state])

    next_state, reward, terminated, truncated, info = env.step(action)

    print("State:", state, " Action:", action, " Next State:", next_state)

    state = next_state
    total_reward += reward
    done = terminated or truncated

if total_reward == 1:
    print("\nGoal Reached!")
else:
    print("\nGoal Not Reached!")

print("Total Reward:", total_reward)

env.close()

Training Completed!

Q-Table:

[[0.74 0.77 0.7  0.74]
 [0.74 0.   0.59 0.  ]
 [0.69 0.   0.   0.  ]
 [0.51 0.   0.   0.  ]
 [0.77 0.81 0.   0.74]
 [0.   0.   0.   0.  ]
 [0.   0.9  0.   0.  ]
 [0.   0.   0.   0.  ]
 [0.81 0.   0.86 0.77]
 [0.81 0.9  0.9  0.  ]
 [0.86 0.95 0.   0.86]
 [0.   0.   0.   0.  ]
 [0.   0.   0.   0.  ]
 [0.   0.9  0.95 0.86]
 [0.9  0.95 1.   0.9 ]
 [0.   0.   0.   0.  ]]

Optimal Path:

State: 0  Action: 1  Next State: 4
State: 4  Action: 1  Next State: 8
State: 8  Action: 2  Next State: 9
State: 9  Action: 1  Next State: 13
State: 13  Action: 2  Next State: 14
State: 14  Action: 2  Next State: 15

Goal Not Reached!
Total Reward: 46
